[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/developer"
  to = "/developer.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/apis"
  to = "/developer"
  status = 301
  force = true

[[redirects]]
  from = "/apis.html"
  to = "/developer"
  status = 301
  force = true

[[redirects]]
  from = "/guaid"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/guaid/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/guaid.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
